### ISSUE TITLE
Widget/Plugin support

### ISSUE THREAD

**Issue by stewartmalik** [tomwolber/Responsive-Toolbar#1]
First of all I'd like to say I love what you're doing here, it seems like this project could go far.

You said you were open to suggestions so here goes. 

Implement a plugin system for the toolbar, so that someone can write a plugin and it will then be pushed onto the toolbar. Like maybe a Twitter plugin, that when you click the Responsive-Toolbar Bookmarklet and then the Twitter icon on the bookmarklet a box pops out automatically filled with shortened link to the page you're already on and so on.
Usernames and passwords could be kept on the machine encrypted in HTML5 Local Storage or something.

**Comment by tomwolber** [comment]
**Thanks for the input!**

I'm not sure how the Twitter example is helpful for web design, especially for _responsive_ web design. Can you please elaborate if you have the time?

**Comment by stewartmalik** [comment]
Oh dear I've been a bit stupid. I didn't even read the description and just read the README.md where it doesn't say anything about web design.

Just ignore me :P
